export const testimonials = [
  {
    id: 1,
    content: "병원 예약률이 40% 올랐어요. 홈페이지 리뉴얼 효과가 확실합니다.",
    author: "김*수",
    role: "성형외과 원장",
    industry: "medical",
  },
  {
    id: 2,
    content: "앱 퀄리티가 대기업 수준이에요. 비용은 절반도 안 들었는데.",
    author: "이*정",
    role: "스타트업 대표",
    industry: "corporate",
  },
  {
    id: 3,
    content: "다른 데서 3번 리뉴얼했는데 여기서 한 번에 끝났어요.",
    author: "박*영",
    role: "쇼핑몰 운영자",
    industry: "fashion",
  },
  {
    id: 4,
    content: "반응형이 진짜 완벽해요. 모바일에서 보는 사람이 70%인데 매출이 올랐어요.",
    author: "최*현",
    role: "패션 브랜드 대표",
    industry: "fashion",
  },
  {
    id: 5,
    content: "SEO 때문에 맡겼는데, 3개월 만에 구글 1페이지에 올라갔어요.",
    author: "정*미",
    role: "마케팅 대행사",
    industry: "corporate",
  },
  {
    id: 6,
    content: "카카오톡으로 실시간 소통이 되니까 불안감이 없었어요.",
    author: "강*호",
    role: "치과 원장",
    industry: "medical",
  },
  {
    id: 7,
    content: "견적이 투명해서 좋았어요. 숨은 비용 하나도 없었습니다.",
    author: "윤*서",
    role: "카페 대표",
    industry: "fnb",
  },
  {
    id: 8,
    content: "디자인 시안 받고 소름 돋았어요. 진짜 해외 사이트 느낌.",
    author: "송*아",
    role: "뷰티 브랜드",
    industry: "fashion",
  },
  {
    id: 9,
    content: "유지보수가 1년 무상이라 부담이 없었어요. 수정도 빠르고.",
    author: "임*태",
    role: "교육 컨설턴트",
    industry: "education",
  },
  {
    id: 10,
    content: "예약 시스템 자동화로 전화 응대가 80% 줄었어요.",
    author: "한*진",
    role: "피부과 원장",
    industry: "medical",
  },
  {
    id: 11,
    content: "매물 관리 시스템 덕분에 업무 시간이 절반으로 줄었습니다.",
    author: "오*석",
    role: "부동산 중개사",
    industry: "realestate",
  },
  {
    id: 12,
    content: "LMS 개발해서 수강생 관리가 한 눈에 됩니다. 매출도 2배.",
    author: "서*은",
    role: "온라인 강사",
    industry: "education",
  },
  {
    id: 13,
    content: "자동화 시스템 도입 후 반복 업무에서 해방됐어요.",
    author: "조*민",
    role: "물류회사 팀장",
    industry: "corporate",
  },
  {
    id: 14,
    content: "기획부터 배포까지 단계별로 확인할 수 있어서 안심했어요.",
    author: "배*진",
    role: "스타트업 CTO",
    industry: "corporate",
  },
  {
    id: 15,
    content: "네이버 상위노출이 되니까 신규 환자가 확 늘었어요.",
    author: "류*원",
    role: "한의원 원장",
    industry: "medical",
  },
  {
    id: 16,
    content: "앱 출시 후 재방문율이 3배 올랐습니다. 대만족.",
    author: "장*혁",
    role: "배달앱 대표",
    industry: "fnb",
  },
] as const;

export type Testimonial = (typeof testimonials)[number];
